import pandas as pd
csv_file = 'NCDB_1999_to_2017.csv'
money_path = 'Traffic Accident Cost Calculation.csv'
y_start = 1999 #inclusive
y_end = 2017   #exlusive
row_only = 0
symbol_remove = ['U','N','Q','UU','QQ','XX','NN','UUUU','XXXX','NNNN']
v_num = [2]
columns_clean = ['C_VEHS','P_ISEV','C_CONF','C_RCFG','V_TYPE','V_YEAR','P_AGE','P_PSN','P_SEX','P_ID','P_SAFE','P_USER','C_RSUR','C_RALN','C_WTHR']
columns_grp = ['V_YEAR','P_SEX','P_AGE']
columns_stats = ['C_YEAR','C_VEHS','C_RSUR','C_RALN','C_WTHR','C_CONF','C_RCFG','V_TYPE','P_SEX','V_AGE_GRP','P_AGE_GRP','P_PSN',"P_SAFE",'P_USER','P_ISEV']
traffic_data_headers = ['C_CASE','C_YEAR','C_VEHS','C_RSUR','C_RALN','C_WTHR','C_CONF','C_RCFG','V_TYPE','P_SEX','V_AGE_GRP','P_AGE_GRP','P_PSN',"P_SAFE",'P_USER','P_ISEV']
dummy_fields = ['C_RSUR','C_RALN','C_WTHR','C_CONF','C_RCFG','V_TYPE','P_PSN',"P_SAFE",'P_USER']
regression = 'tree'
# regression = 'lr'
time = True
test_size = 0.2
year = 2017 # year for test and earlier for training
interval = 2017-1999
classweight = "balanced"
C = [1.0]
# C =np.append([1.0],np.logspace(-4, 4, 30))
penalty = ['l1', 'l2']
solver='saga'
multi_class='multinomial'
cv = 0
# cv =[3,5]
 # C = range(10,30,10)
 # penalty = [0,0.5,1.0]
max_dep = 40
#split_type = ["best","random"]
split_type = ["best"]
#crt_type = ["gini","entropy"]
crt_type = ["gini"]
